K8s guide
jobrunr/website pull request #26
Opened 2024-07-23 08:21 UTC by dumnicki

2024-07-23 13:37 UTC, auloin requested changes

2024-07-23 13:37 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +## Optional - secure your JobRunr dashboard
Nice section. But I don't find it really useful in this context. I'd simply mention that if they have enabled authentication, KEDA supports different kind of authentication schemes and link to the official docs. Another reason is I don't want to advertise basic auth.

2024-07-23 13:37 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +No recurring jobs can be executed if no `BackgroundJobServers` are running. We recommend having always 1 `BackgroundJobServer` running.
Should be on the same line as the previous sentence. Also I believe this may be more than a recommendation but a requirement in some scenarios? I wonder if we need the sentence.

2024-07-23 13:37 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +The workers' usage is updated at every [background job server poll interval](documentation/configuration/spring#advanced-configuration). Therefore, setting a higher poll interval in KEDA when using o
I don't totally agree with this statement. While it's true that we save the maxOccupiedWorkers every poll interval, KEDA still needs to retrieve all the background job stats from the DB just to compute the usage. We can avoid extra DB load and CPU load by increasing the poll interval, am I wrong?

2024-07-23 13:37 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +`usage` - percentage value of total usage of workers
Should we usage bullet points here too?

2024-07-23 13:37 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +`latency` - time the oldest Job has spent in the queue in milliseconds.
Should we usage bullet points here too?

2024-07-24 07:49 UTC, dumnicki commented on themes/casper3/assets/js/codetabs.js
It was to fix the codetabs that I used in the previous version of the guide to provide a Maven/Gradle tabs for commands. I don't use it in the current version anymore.

2024-07-24 08:03 UTC, dumnicki commented on content/en/guides/advanced/k8s-autoscaling.md
> +You can follow this guide step-by-step to deploy your existing JobRunr application. If you want to learn how to include and use JobRunr in your project, follow [this guide]({{<ref "guides/intro/java-
I think even better would be:
> You can follow this guide step-by-step to deploy your existing JobRunr application. If you're new to JobRunr, start by following [this guide]({{<ref "guides/intro/java-lambda.md">}}) to learn how to include and use it in your project.

2024-07-24 09:02 UTC, dumnicki commented on content/en/guides/advanced/k8s-autoscaling.md
> +- your application running JobRunr dashboard and your application running JobRunr `BackgroundJobServer`.
Currently the metrics api is available only if the dashboard is enabled. Background job server has to be enabled but not necessarily separately. Maybe I should explain it in the guide.

2024-07-24 16:13 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +You can follow this guide step-by-step to deploy your existing JobRunr application. If you want to learn how to include and use JobRunr in your project, follow [this guide]({{<ref "guides/intro/java-
Like the general but still not would not use 
> start by following

It sounds like an order instead of an invitation.

2024-07-25 14:21 UTC, auloin requested changes

2024-07-25 14:21 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +## Optional - secure your JobRunr dashboard
```suggestion
## Autoscaling your secured JobRunr dashboard
```

2024-07-26 13:23 UTC, auloin requested changes

2024-07-26 13:23 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +## JobRunr Pro metrics api
```suggestion
## JobRunr Pro metrics API
```

2024-07-26 13:23 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +If you are planning to run jobs with long execution times, you might want to prevent Kubernetes from terminating your replicas that are still processing a long-running job. To do that, you can modify
```suggestion
If you are planning to run jobs with long execution times, you might want to prevent Kubernetes from terminating your replicas that are still processing a long-running job. To do that, you can modify the graceful termination period for your pods in Kubernetes. This can be done by setting the `terminationGracePeriodSeconds` property in your Pod `spec`. You'll also have to configure the duration to wait before interrupting jobs in JobRunr. 

The termination period of both Kubernetes and JobRunr can be determined by the maximum expected runtime of your jobs. Imagine your longest running job takes 1 hour to complete. Then your graceful period should be greater than the execution time of that job, for example an 1 hour and 30 minutes.

You can configure your deployment as follows:
```

2024-07-26 13:23 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +Similar wait period would also have to be configured in JobRunr. There are multiple different options to [configure JobRunr](/documentation/configuration/). Since we are using the `jobrunr-pro-spring
```suggestion
Similarly, a termination period would also have to be configured for JobRunr. There are multiple different options to [configure JobRunr](/documentation/configuration/). Since we are using the `jobrunr-pro-spring-boot-3-starter` dependency, we can add the following property to the `application.properties`:
```

2024-07-26 13:23 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +> If you are curious about how Kubernetes terminates the Pods, you can follow [this link](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination).
```suggestion
> There are two things to note. First, the Kubernetes termination period should match or be larger than the JobRunr one. Second, contrary to JobRunr, Kubernetes does not terminate before the end of the configured period. So, even though, JobRunr may have stopped after only 10 minutes, the Pod may remain in terminating for long time doing nothing. If you are curious about how Kubernetes terminates the Pods, you can follow [this link](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination).
```

2024-07-26 13:23 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +We have defined three triggers, and when any of these triggers meet the criteria, KEDA will start scaling. The Horizontal Pod Autoscaler (HPA), which drives the scaling, will calculate proposed repli
Should we add this to the following subsection instead? And make it conditional because not all user will be configured 3 triggers at the same time?

Another approach, would be to add it to the `Testing the autoscaling` section and illustrate it?

2024-07-26 13:23 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +We have defined three triggers, and when any of these triggers meet the criteria, KEDA will start scaling. The Horizontal Pod Autoscaler (HPA), which drives the scaling, will calculate proposed repli
```suggestion
We have defined three triggers, and when any of these triggers meet the criteria, KEDA will start scaling. The Horizontal Pod Autoscaler (HPA), which drives the scaling, will process the proposed replica counts for each trigger and use the highest one to scale the workload to.
```

Should we add a link to HPA documentation? I don't know if we already did.

2024-07-31 11:37 UTC, rdehuyss commented on content/en/guides/advanced/k8s-autoscaling.md
> +description: This guide will help you use Jobrunr Pro features to create a Kubernetes deployment of your application that autoscales based on JobRunr provided metrics.
```suggestion
description: This guide will help you to create a Kubernetes deployment of your application that autoscales based on metrics provided by JobRunr Pro.
```

2024-07-31 11:44 UTC, rdehuyss commented on content/en/guides/advanced/k8s-autoscaling.md
> +> The separation of the `web` and the `workers` is there to enable us to scale those two different parts separately. The dashboard deployment can be scaled independently to handle varying levels of u
I would not mention scaling the dashboard based on traffic. Most of the time, it is only engineers from inside the company so the load will be really low. Also, multiple dashboards hit the DB rather hard due to a query (the one that shows how many jobs are enqueued / scheduled / ... ) only used in the dashboard.

2024-07-31 12:02 UTC, auloin commented on content/en/guides/advanced/k8s-autoscaling.md
> +> The separation of the `web` and the `workers` is there to enable us to scale those two different parts separately. The dashboard deployment can be scaled independently to handle varying levels of u
I would update 

`The dashboard deployment can be scaled independently to handle varying levels of user traffic without affecting the job processing capabilities.` 

to 

`The web deployment can be scaled independently to handle varying levels of user traffic without affecting the job processing capabilities.`

Then the example makes sense, as they may have integrated the JobRunr dashboard with an existing web service from which jobs are enqueued (or used for other kind of services).

2024-07-31 12:17 UTC, dumnicki commented on content/en/guides/advanced/k8s-autoscaling.md
> +> The separation of the `web` and the `workers` is there to enable us to scale those two different parts separately. The dashboard deployment can be scaled independently to handle varying levels of u
```suggestion
> The separation of the `web` and the `workers` is there to enable us to scale the number of replicas responsible for processing jobs, while maintaining only one instance of the dashboard. The `BackgroundJobServer` can scale based on job queue metrics, ensuring optimal job processing efficiency. This separation ensures that even if no `BackgroundJobServers` are currently running, scheduled jobs will still be processed as the autoscaling configuration will start a new `BackgroundJobServer` on demand.
```

2024-08-01 11:44 UTC, merged